In [1]:
import scipy.io as sio

wave = sio.loadmat('../data/final_data_sensor_data_x306y166_10.mat')

In [22]:
print(wave['final_data'][0][0][2].shape)

(10, 3)


In [2]:
import numpy as np
# Wavelet data (32, 32, 1000, 64) = (scan, transducer, time, frequency)
wavelet = np.random.randn(32, 32, 1000, 64)
# Phase data (32, 32, 64, 64) = (scan, transducer, gridN, gridN)
phase = np.random.randn(32, 32, 64, 64)
# Defeat label (defeat_num, 3) = (defeat_num, [posx, posy, radius])
defeat = np.random.randn(5, 3)

mat_file = {'wave': wavelet, 'phase': phase, 'defeat': defeat}
print(mat_file.keys())


dict_keys(['wave', 'phase', 'defeat'])
defeat:  [[-1.23124241  0.22226293 -1.84552674]
 [ 0.56349057  0.65098655 -0.26963244]
 [-0.97344152 -0.47418434 -1.61349992]
 [ 1.3941215   0.29071678  0.16161521]
 [ 0.16074837  0.5154749   1.57467707]]


In [ ]:
defeat = [[1, ]]
print('defeat: ', mat_file['defeat'])